/**:
  ros__parameters:
    ############ system configuration ############
    # Data logging
    log_to_file: true
    log_debug: true
    log_enabled: [
        ## ADD LOGGER IDS HERE
        # tactic
        "tactic",
        # "tactic.pipeline",
        "tactic.module",
        # "tactic.module.live_mem_manager",
        # "tactic.module.graph_mem_manager",
        # pipeline specific
        "lidar.pipeline",
        # "lidar.aeva_converter",
        # "lidar.preprocessing_doppler",
        # "lidar.odometry_icp",
        # "lidar.odometry_doppler",
        # "lidar.odometry_map_maintenance",
        # "lidar.vertex_test",
        # "lidar.localization_map_recall",
        # "lidar.localization_icp",
      ]

    ############ tactic configuration ############
    tactic:
      enable_parallelization: false
      preprocessing_skippable: false
      odometry_mapping_skippable: false
      localization_skippable: false

      task_queue_num_threads: 1
      task_queue_size: -1

      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 30.0

      save_odometry_result: true
      save_localization_result: true
      visualize: false

      # localization interval threshold
      use_loc_threshold: true
      loc_threshold: 100 # num frames

      rviz_loc_path_offset: [0., 0., 0.]

    ############ pipeline configuration ############
    pipeline:
      type: lidar

      preprocessing: [
          # preprocessing thread modules
          "conversion",
          "filtering",
        ]

      odometry: [
          # odometry and mapping thread modules
          "icp",
          # "doppler", 
          "mapping",
          "vertex_test",
          "memory",
        ]

      localization: [
          # localization thread modules
          "recall",
          "icp",
          "memory",
        ]

      # submap creation thresholds
      submap_translation_threshold: 10.0 # in meters
      submap_rotation_threshold: 30.0 # in degrees

    preprocessing:
      conversion:
        type: lidar.aeva_converter

        visualize: false

      filtering:
        # if using odometry_icp, change type below to `lidar.preprocessing`
        # if using odometry_doppler, change type below to `lidar.preprocessing_doppler`
        type: lidar.preprocessing
        num_threads: 10

        # preprocessing parameters
        crop_range: 150.0
        # 
        vertical_angle_res: 0.0020943951 # vertical angle resolution in radians (0.12 deg w/ 30 vertical FOV) (0020943951)
        polar_r_scale: 2.0 # polar_r_scale x vertical_angle_res = nearest neighbor search radius for normal computation
        r_scale: 4.0 # scale down point range by this value after taking log, whatever works
        h_scale: 0.5167 # scale down yaw(phi) by this value so that vertical resolution ~= horizontal resolution (0.062 deg / 0.12 deg = 0.5167)
        #
        frame_voxel_size: 0.3 # grid subsampling voxel size
        filter_normal: true
        #
        num_sample1: 10000 # max number of sample after filtering based on planarity
        min_norm_score1: 0.95 # min planarity score
        #
        num_sample2: 20000 # max number of sample after filtering based on planarity
        min_norm_score2: 0.0 # 0.2 is when the incident angle 5/12 * pi
        min_normal_estimate_dist: 2.0 # minimum distance to estimate normal in meters
        max_normal_estimate_angle: 0.42 # must <1/2, this value will be timed by M_PI
        #
        cluster_num_sample: 20000 # maxnumber of sample after removing isolated points

        # preprocessing_doppler parameters
        azimuth_res: 0.00349066
        azimuth_start: -0.872665
        azimuth_end: 0.872665
        num_rows: 80
        num_cols: 501
        min_dist: 20
        max_dist: 150
        #
        # we only use back sensor! front sensor does not have good gyro
        active_lidars: [false, false, false, true]    # 0: front, 1: left, 2: right, 3: back
        active_gyros: [false, false, false, true]     # 0: front, 1: left, 2: right, 3: back
        root_path: "/home/asrl-katya/ASRL/doppler_odom/sensor_config/aeva"    # point this to where we find the model
        model_name: "mar4_aeries2_lrvar_bp4-rim_vp3-imv-g_r5-150-e5_s0123_a0p1_aplat_newcalib_redo"
        downsample_steps: 2 # after image projection 
        #
        bias_input_feat: ["range", "intensity", "medianrv"]     # "range", "azimuth", "ransac_fvel", "ransac_yvel" ,  "gtvz", "gtox", "gtoy",
        var_input_feat: ["intensity", "medianrv", "rv_var5"]    # rv_stddev5 "range", "azimuth", "ransac_fvel", "ransac_yvel" ,  "gtvz", "gtox", "gtoy",
        bias_polyorder: 3
        var_polyorder: 2
        median_sensorid: 3
        mm_azi: [-55.0, 55.0] # deg
        azi_res: 0.2          # deg

        visualize: false

    odometry:
      icp:
        type: lidar.odometry_icp

        # continuous time estimation
        use_trajectory_estimation: true
        traj_num_extra_states: 0
        traj_lock_prev_pose: true
        traj_lock_prev_vel: false
        traj_qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]
        
        use_point_association: false

        use_radial_velocity: false
        rv_cov: 1.0
        rv_loss_threshold: 1.0

        use_velocity_prior: false
        vp_cov: [1000.0, 0.001, 1000.0, 1000.0, 1000.0, 1000.0]

        # ICP parameters
        num_threads: 10
        first_num_steps: 3
        initial_max_iter: 6
        initial_max_pairing_dist: 3.0
        initial_max_planar_dist: 1.0
        refined_max_iter: 50
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.3
        averaging_num_steps: 3
        # steam parameters
        verbose: false
        max_iterations: 1

        # threshold
        min_matched_ratio: 0.0

        visualize: false

      doppler:
        type: lidar.odometry_doppler
        # continuous time estimation
        use_trajectory_estimation: true
        traj_num_extra_states: 0
        traj_lock_prev_pose: false
        traj_lock_prev_vel: false
        traj_qc_diag: [1.0, 0.001, 0.001, 0.001, 0.001, 1.0]


        # doppler odom parameters
        num_threads: 10
        num_sensors: 1
        ransac_seed: 0
        ransac_gyro: false
        ransac_max_iter: 40
        ransac_thres: 0.4
        ransac_min_range: 5.0
        integration_steps: 100
        zero_vel_tol: 0.03

        min_dist_lidar_center: 5.0 
        max_dist_lidar_center: 150.0 

        P0inv: [1e6, 1e6, 1e6, 1e8, 1e8, 1e8]

        # aeva_hq
        Qkinv: [3.0e+2, 4.1e+3, 1.9e+3, 6.2e+4, 3.6e+4, 4.1e+5]
        Qzinv: [0.0e0, 1.3e2, 3.2e2, 5.1e4, 5.1e4, 0.0e0]

        # threshold
        min_matched_ratio: 0.0

        visualize: false

      mapping:
        type: lidar.odometry_map_maintenance_v2

        map_voxel_size: 0.2

        crop_range_front: 150.0
        back_over_front_ratio: 1.0

        point_life_time: 10.0

        visualize: false

      vertex_test:
        type: lidar.vertex_test

        max_translation: 0.5
        max_rotation: 3.0

      memory:
        type: "live_mem_manager"

        window_size: 5 # unload data older than this many keyframes

    localization:
      recall:
        type: lidar.localization_map_recall

        map_version: "pointmap"

        visualize: false

      icp:
        type: lidar.localization_icp

        use_pose_prior: true

        # ICP parameters
        num_threads: 10
        first_num_steps: 3
        initial_max_iter: 6
        initial_max_pairing_dist: 5.0
        initial_max_planar_dist: 1.0
        refined_max_iter: 100
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.3
        averaging_num_steps: 3

        # steam parameters
        verbose: false
        max_iterations: 1

        # threshold
        min_matched_ratio: 0.3

      memory:
        type: "graph_mem_manager"

        vertex_life_span: 5
        window_size: 3