/**:
  ros__parameters:
    ############ system configuration ############
    # Data logging
    log_to_file: true
    log_debug: true
    log_enabled: [
        ## ADD LOGGER IDS HERE
        # tactic
        # "tactic",
        # "tactic.pipeline",
        # "tactic.module",
        # "tactic.module.live_mem_manager",
        # "tactic.module.graph_mem_manager",
        # pipeline specific
        "lidar.pipeline",
        # "lidar.aeva_converter",
        "lidar.preprocessing",
        # "lidar.odometry_icp",
        "lidar.odometry_map_maintenance",
        # "lidar.vertex_test",
        # "lidar.localization_map_recall",
        # "lidar.localization_icp",
      ]

    ############ tactic configuration ############
    tactic:
      enable_parallelization: false
      preprocessing_skippable: false
      odometry_mapping_skippable: false
      localization_skippable: false

      task_queue_num_threads: 1
      task_queue_size: -1

      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 30.0

      save_odometry_result: true
      save_localization_result: true
      visualize: true

      rviz_loc_path_offset: [0., 0., 0.]

    ############ pipeline configuration ############
    pipeline:
      type: lidar

      preprocessing: [
          # preprocessing thread modules
          "conversion",
          "filtering",
        ]

      odometry: [
          # odometry and mapping thread modules
          "icp",
          "mapping",
          "vertex_test",
          "memory",
        ]

      localization: [
          # localization thread modules
          "recall",
          "icp",
          "memory",
        ]

      # submap creation thresholds
      submap_translation_threshold: 10.0 # in meters
      submap_rotation_threshold: 30.0 # in degrees

    preprocessing:
      conversion:
        type: lidar.aeva_converter

        visualize: true

      filtering:
        type: lidar.preprocessing_v2

        num_threads: 1

        crop_range: 60.0

        frame_voxel_size: 0.15 # grid subsampling voxel size

        visualize: true

    odometry:
      icp:
        type: lidar.odometry_icp

        # motion prior terms
        trajectory_smoothing: true
        qc_diagonal: [1.0, 0.1, 0.1, 0.1, 0.1, 1.0]

        # ICP parameters
        num_threads: 1
        first_num_steps: 3
        initial_max_iter: 6
        initial_max_pairing_dist: 3.0
        initial_max_planar_dist: 1.0
        refined_max_iter: 100
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.3
        averaging_num_steps: 3
        # steam parameters
        verbose: false
        max_iterations: 1

        # threshold
        min_matched_ratio: 0.5

        visualize: true

      mapping:
        type: lidar.odometry_map_maintenance

        map_voxel_size: 0.3

        point_life_time: 10.0

        visualize: true

      vertex_test:
        type: lidar.vertex_test

        max_translation: 1.0
        max_rotation: 10.0

      memory:
        type: "live_mem_manager"

        window_size: 5 # unload data older than this many keyframes

    localization:
      recall:
        type: lidar.localization_map_recall

        map_version: "pointmap"

        visualize: true

      icp:
        type: lidar.localization_icp

        use_pose_prior: true

        # ICP parameters
        num_threads: 1
        first_num_steps: 3
        initial_max_iter: 6
        initial_max_pairing_dist: 5.0
        initial_max_planar_dist: 1.0
        refined_max_iter: 100
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.3
        averaging_num_steps: 3

        # steam parameters
        verbose: false
        max_iterations: 1

        # threshold
        min_matched_ratio: 0.3

      memory:
        type: "graph_mem_manager"

        vertex_life_span: 5
        window_size: 3
